name: Promover cambios a ambientes

on:
  workflow_dispatch:

concurrency:
  group: promote-environments-secuencial
  cancel-in-progress: false

jobs:
  cpromover:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio completo
      - name: Checkout repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Crear los PRs autom치ticos hacia cada ambiente
      - name: Crear y fusionar PRs a QA, STG y PROD
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const environments = ['qa', 'stg', 'prod'];

            for (const env of environments) {
              const prs = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "open",
                head: `${context.repo.owner}:ms-documents-bs-final`,
                base: env,
              });

              if (prs.data.length === 0) {
                console.log(`Creando PR desde ms-documents-bs-final hacia ${env}...`);
                const { data: newPr } = await github.rest.pulls.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  head: "ms-documents-bs-final",
                  base: env,
                  title: `PR autom치tico: Promover cambios a ${env.toUpperCase()}`,
                  body: `Este PR fue generado autom치ticamente para promover cambios desde ms-documents-bs-final hacia ${env.toUpperCase()}.`,
                  draft: false
                });

                console.log(`Intentando fusionar PR #${newPr.number} hacia ${env}...`);
                try {
                  await github.rest.pulls.merge({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: newPr.number,
                    merge_method: 'squash'
                  });
                  console.log(`PR #${newPr.number} fusionado autom치ticamente.`);
                } catch (mergeError) {
                  console.error(`No se pudo fusionar el PR #${newPr.number}:`, mergeError.message);
                }

              } else {
                console.log(`Ya existe un PR abierto hacia ${env}.`);
              }
            }

